### ISSUE TITLE
Updating while using custom DNS

### ISSUE THREAD

**Issue by bizzar721** [WerWolv98/EdiZon_ConfigsAndScripts#19]
Thanks for all the hard work put into this project.  I just wanted to inform you that updating from within EdiZon is blocked while using the standard custom DNS of:
“Primary DNS” to 104.236.106.125
“Secondary DNS” to 62.210.147.20

**Comment by WerWolv98** [comment]
Thanks! Nothing I can fix though. You would have to talk to the owner of the DNS to unblock werwolv.net
