### ISSUE TITLE
can you support  "Xenoblade 2 DLC: Torna the Golden Country"  ?

### ISSUE THREAD

**Issue by manondidi** [WerWolv98/EdiZon_ConfigsAndScripts#40]
single  card of "Torna the Golden Country"    version    not    "Xenoblade 2 +dlc patch" version

**Comment by WerWolv98** [comment]
EdiZon has a config for Xenoblade Chronicles 2 here: https://github.com/WerWolv98/EdiZon_ConfigsAndScripts/blob/master/Configs/0100E95004038000.json
If that doesn't work, somebody has to develop a config for it. I don't have the game myself so you need to find somebody else. Config requests are no issues

**Comment by manondidi** [comment]
can you develop it if i can give you the nsp file?
